---
- name: Install Keepalived package
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: true
  when: haproxy_keepalived_enabled

- name: Deploy Keepalived configuration file
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when: haproxy_keepalived_enabled
  notify: restart keepalived

- name: Ensure Keepalived service is started and enabled
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
  when: haproxy_keepalived_enabled
