---
# handlers file for ansible-role-haproxy

- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true

- name: reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded

- name: restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: true
